module.exports = [
  {
    id: 1,
    name: "Fehér akác",
    latin: "Robinia pseudoacacia",
    phase: [
      "rügyfakadás",
      "virágzás kezdete",
      "virágzás",
      "virágzás vége",
      "lombszíneződés kezdete",
      "lombhullás kezdete",
    ],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Fák",
  },
  {
    id: 2,
    name: "Kislevelű hárs",
    latin: "Tilia cordata",
    phase: [
      "rügyfakadás",
      "virágzás kezdete",
      "virágzás",
      "virágzás vége",
      "lombszíneződés kezdete",
      "lombhullás kezdete",
    ],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Fák",
  },
  {
    id: 3,
    name: "Közönséges nyír",
    latin: "Betula pendula",
    phase: [
      "rügyfakadás",
      "virágzás kezdete",
      "virágzás",
      "virágzás vége",
      "lombszíneződés kezdete",
      "lombhullás kezdete",
    ],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Fák",
  },
  {
    id: 4,
    name: "Vadgesztenye",
    latin: "Aesculus hippocastanum",
    phase: [
      "rügyfakadás",
      "virágzás kezdete",
      "virágzás",
      "virágzás vége",
      "termésérés kezdete",
      "lombszíneződés kezdete",
      "lombhullás kezdete",
    ],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Fák",
  },
  {
    id: 5,
    name: "Húsos som",
    latin: "Cornus mas",
    phase: [
      "rügyfakadás",
      "virágzás kezdete",
      "virágzás",
      "virágzás vége",
      "termésérés kezdete",
      "lombszíneződés kezdete",
      "lombhullás kezdete",
    ],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Cserjék",
  },
  {
    id: 6,
    name: "Közönséges mogyoró",
    latin: "Corylus avellana",
    phase: [
      "rügyfakadás",
      "virágzás kezdete",
      "virágzás",
      "virágzás vége",
      "termésérés kezdete",
      "lombszíneződés kezdete",
      "lombhullás kezdete",
    ],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Cserjék",
  },
  {
    id: 7,
    name: "Fekete bodza",
    latin: "Sambucus nigra",
    phase: [
      "rügyfakadás",
      "virágzás kezdete",
      "virágzás",
      "virágzás vége",
      "termésérés kezdete",
      "lombszíneződés kezdete",
      "lombhullás kezdete",
    ],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Cserjék",
  },
  {
    id: 8,
    name: "Orgona",
    latin: "Syringa vulgaris",
    phase: [
      "rügyfakadás",
      "virágzás kezdete",
      "virágzás",
      "virágzás vége",
      "lombszíneződés kezdete",
      "lombhullás kezdete",
    ],
    photo: "../../assets/image/kozonseges_orgona.jpg",
    category: "Cserjék",
  },
  {
    id: 9,
    name: "Aranyfa",
    latin: "Forsythia",
    phase: [
      "rügyfakadás",
      "virágzás kezdete",
      "virágzás",
      "virágzás vége",
      "lombszíneződés kezdete",
      "lombhullás kezdete",
    ],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Cserjék",
  },
  {
    id: 10,
    name: "Őszi kikerics",
    latin: "Colchicum autumnale",
    phase: ["virágzás kezdete", "virágzás", "virágzás vége"],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Lágyszárúak",
  },
  {
    id: 11,
    name: "Gyöngyvirág",
    latin: "Convallaria majalis",
    phase: ["virágzás kezdete", "virágzás", "virágzás vége"],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Lágyszárúak",
  },
  {
    id: 12,
    name: "Pongyola pitypang",
    latin: "Taraxacum officinale",
    phase: ["virágzás kezdete", "virágzás", "virágzás vége"],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Lágyszárúak",
  },
  {
    id: 13,
    name: "Pipacs",
    latin: "Papaver rhoeas",
    phase: ["virágzás kezdete", "virágzás", "virágzás vége"],
    photo: "../../assets/image/Feher_akac.jpg",
    category: "Lágyszárúak",
  },
];
